//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/07/08 - 22:06:35
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class almacenDTO
    {
        [DataMember()]
        public Int32 ID_Almacen { get; set; }

        [DataMember()]
        public String year { get; set; }

        [DataMember()]
        public String nombre_almacen { get; set; }

        [DataMember()]
        public String direccion { get; set; }

        [DataMember()]
        public String estado { get; set; }

        [DataMember()]
        public List<requerimientoDTO> requerimiento { get; set; }

        public almacenDTO()
        {
        }

        public almacenDTO(Int32 iD_Almacen, String year, String nombre_almacen, String direccion, String estado, List<requerimientoDTO> requerimiento)
        {
			this.ID_Almacen = iD_Almacen;
			this.year = year;
			this.nombre_almacen = nombre_almacen;
			this.direccion = direccion;
			this.estado = estado;
			this.requerimiento = requerimiento;
        }
    }
}
