//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/07/08 - 22:06:35
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class catalogoDTO
    {
        [DataMember()]
        public String ID_Catalogo { get; set; }

        [DataMember()]
        public String tipo_bien { get; set; }

        [DataMember()]
        public String unidad_medida { get; set; }

        [DataMember()]
        public String nombre_bien { get; set; }

        [DataMember()]
        public List<requerimiento_detalleDTO> requerimiento_detalle { get; set; }

        public catalogoDTO()
        {
        }

        public catalogoDTO(String iD_Catalogo, String tipo_bien, String unidad_medida, String nombre_bien, List<requerimiento_detalleDTO> requerimiento_detalle)
        {
			this.ID_Catalogo = iD_Catalogo;
			this.tipo_bien = tipo_bien;
			this.unidad_medida = unidad_medida;
			this.nombre_bien = nombre_bien;
			this.requerimiento_detalle = requerimiento_detalle;
        }
    }
}
