//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/07/08 - 22:06:36
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class entidadDTO
    {
        [DataMember()]
        public String Ruc { get; set; }

        [DataMember()]
        public String nombre_entidad { get; set; }

        [DataMember()]
        public String direccion { get; set; }

        [DataMember()]
        public String telefono { get; set; }

        public entidadDTO()
        {
        }

        public entidadDTO(String ruc, String nombre_entidad, String direccion, String telefono)
        {
			this.Ruc = ruc;
			this.nombre_entidad = nombre_entidad;
			this.direccion = direccion;
			this.telefono = telefono;
        }
    }
}
