//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/07/08 - 22:06:36
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class proyectoDTO
    {
        [DataMember()]
        public Int32 ID_Proyecto { get; set; }

        [DataMember()]
        public Nullable<Int32> ID_Usuario { get; set; }

        [DataMember()]
        public String year_ejec { get; set; }

        [DataMember()]
        public String nombre { get; set; }

        [DataMember()]
        public String estado { get; set; }

        [DataMember()]
        public usuarioDTO usuario { get; set; }

        public proyectoDTO()
        {
        }

        public proyectoDTO(Int32 iD_Proyecto, Nullable<Int32> iD_Usuario, String year_ejec, String nombre, String estado, usuarioDTO usuario)
        {
			this.ID_Proyecto = iD_Proyecto;
			this.ID_Usuario = iD_Usuario;
			this.year_ejec = year_ejec;
			this.nombre = nombre;
			this.estado = estado;
			this.usuario = usuario;
        }
    }
}
