//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/07/08 - 22:06:37
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class requerimiento_detalleDTO
    {
        [DataMember()]
        public Int32 ID_RequerimientoDetalle { get; set; }

        [DataMember()]
        public Nullable<Int32> ID_Requerimiento { get; set; }

        [DataMember()]
        public String ID_Catalogo { get; set; }

        [DataMember()]
        public String ID_UnidadMedida { get; set; }

        [DataMember()]
        public Nullable<Double> cantidad { get; set; }

        [DataMember()]
        public Nullable<Double> valor_referencial { get; set; }

        [DataMember()]
        public catalogoDTO catalogo { get; set; }

        [DataMember()]
        public requerimientoDTO requerimiento { get; set; }

        [DataMember()]
        public unidad_medidaDTO unidad_medida { get; set; }

        public requerimiento_detalleDTO()
        {
        }

        public requerimiento_detalleDTO(Int32 iD_RequerimientoDetalle, Nullable<Int32> iD_Requerimiento, String iD_Catalogo, String iD_UnidadMedida, Nullable<Double> cantidad, Nullable<Double> valor_referencial, catalogoDTO catalogo, requerimientoDTO requerimiento, unidad_medidaDTO unidad_medida)
        {
			this.ID_RequerimientoDetalle = iD_RequerimientoDetalle;
			this.ID_Requerimiento = iD_Requerimiento;
			this.ID_Catalogo = iD_Catalogo;
			this.ID_UnidadMedida = iD_UnidadMedida;
			this.cantidad = cantidad;
			this.valor_referencial = valor_referencial;
			this.catalogo = catalogo;
			this.requerimiento = requerimiento;
			this.unidad_medida = unidad_medida;
        }
    }
}
