//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/07/08 - 22:06:38
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class unidad_medidaDTO
    {
        [DataMember()]
        public String ID_UnidadMedida { get; set; }

        [DataMember()]
        public String nombre { get; set; }

        [DataMember()]
        public List<requerimiento_detalleDTO> requerimiento_detalle { get; set; }

        public unidad_medidaDTO()
        {
        }

        public unidad_medidaDTO(String iD_UnidadMedida, String nombre, List<requerimiento_detalleDTO> requerimiento_detalle)
        {
			this.ID_UnidadMedida = iD_UnidadMedida;
			this.nombre = nombre;
			this.requerimiento_detalle = requerimiento_detalle;
        }
    }
}
