//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/07/08 - 22:06:38
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class usuarioDTO
    {
        [DataMember()]
        public Int32 ID_Usuario { get; set; }

        [DataMember()]
        public Nullable<Int32> ID_Departamento { get; set; }

        [DataMember()]
        public String DNI { get; set; }

        [DataMember()]
        public String password { get; set; }

        [DataMember()]
        public String nombres { get; set; }

        [DataMember()]
        public String apellidos { get; set; }

        [DataMember()]
        public Nullable<DateTime> fecha_nacimiento { get; set; }

        [DataMember()]
        public String email { get; set; }

        [DataMember()]
        public String celular { get; set; }

        [DataMember()]
        public String estado { get; set; }

        [DataMember()]
        public departamentoDTO departamento { get; set; }

        [DataMember()]
        public IEnumerable<proyectoDTO> proyecto { get; set; }

        [DataMember()]
        public List<requerimientoDTO> requerimiento { get; set; }

        public usuarioDTO()
        {
        }

        public usuarioDTO(Int32 iD_Usuario, Nullable<Int32> iD_Departamento, String dNI, String password, String nombres, String apellidos, Nullable<DateTime> fecha_nacimiento, String email, String celular, String estado, departamentoDTO departamento, IEnumerable<proyectoDTO> proyecto, List<requerimientoDTO> requerimiento)
        {
			this.ID_Usuario = iD_Usuario;
			this.ID_Departamento = iD_Departamento;
			this.DNI = dNI;
			this.password = password;
			this.nombres = nombres;
			this.apellidos = apellidos;
			this.fecha_nacimiento = fecha_nacimiento;
			this.email = email;
			this.celular = celular;
			this.estado = estado;
			this.departamento = departamento;
			this.proyecto = proyecto;
			this.requerimiento = requerimiento;
        }
    }
}
