//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/07/08 - 22:06:39
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Dominio.Dtos;
using PersistenciaDatos;

namespace Dominio.Convertidores
{

    /// <summary>
    /// Assembler for <see cref="almacen"/> and <see cref="almacenDTO"/>.
    /// </summary>
    public static partial class almacenAssembler
    {
        
        public static almacen ToEntity(this almacenDTO dto)
        {
            if (dto == null) return null;

            var entity = new almacen();

            entity.ID_Almacen = dto.ID_Almacen;
            entity.year = dto.year;
            entity.nombre_almacen = dto.nombre_almacen;
            entity.direccion = dto.direccion;
            entity.estado = dto.estado;

         

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="almacen"/> to an instance of <see cref="almacenDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="almacen"/> to convert.</param>
        public static almacenDTO ToDTO(this almacen entity)
        {
            if (entity == null) return null;

            var dto = new almacenDTO();

            dto.ID_Almacen = entity.ID_Almacen;
            dto.year = entity.year;
            dto.nombre_almacen = entity.nombre_almacen;
            dto.direccion = entity.direccion;
            dto.estado = entity.estado;

           

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="almacenDTO"/> to an instance of <see cref="almacen"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<almacen> ToEntities(this IEnumerable<almacenDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="almacen"/> to an instance of <see cref="almacenDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<almacenDTO> ToDTOs(this IEnumerable<almacen> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }
        public static void Actualizar(Dominio.Dtos.almacenDTO dto, PersistenciaDatos.almacen entity)
        {
            entity.ID_Almacen = dto.ID_Almacen;
            entity.year = dto.year;
            entity.nombre_almacen = dto.nombre_almacen;
            entity.direccion = dto.direccion;
            entity.estado = dto.estado;

        }
    }
}
