//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/07/08 - 22:06:40
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Dominio.Dtos;
using PersistenciaDatos;

namespace Dominio.Convertidores
{

    /// <summary>
    /// Assembler for <see cref="entidad"/> and <see cref="entidadDTO"/>.
    /// </summary>
    public static partial class entidadAssembler
    {
       
        public static entidad ToEntity(this entidadDTO dto)
        {
            if (dto == null) return null;

            var entity = new entidad();

            entity.Ruc = dto.Ruc;
            entity.nombre_entidad = dto.nombre_entidad;
            entity.direccion = dto.direccion;
            entity.telefono = dto.telefono;

          

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="entidad"/> to an instance of <see cref="entidadDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="entidad"/> to convert.</param>
        public static entidadDTO ToDTO(this entidad entity)
        {
            if (entity == null) return null;

            var dto = new entidadDTO();

            dto.Ruc = entity.Ruc;
            dto.nombre_entidad = entity.nombre_entidad;
            dto.direccion = entity.direccion;
            dto.telefono = entity.telefono;

           

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="entidadDTO"/> to an instance of <see cref="entidad"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<entidad> ToEntities(this IEnumerable<entidadDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="entidad"/> to an instance of <see cref="entidadDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<entidadDTO> ToDTOs(this IEnumerable<entidad> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

        public static void Actualizar(Dominio.Dtos.entidadDTO dto, PersistenciaDatos.entidad entity)
        {
            entity.Ruc = dto.Ruc;
            entity.nombre_entidad = dto.nombre_entidad;
            entity.direccion = dto.direccion;
            entity.telefono = dto.telefono;

        }

    }
}
