//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/07/08 - 22:06:40
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Dominio.Dtos;
using PersistenciaDatos;

namespace Dominio.Convertidores
{

    /// <summary>
    /// Assembler for <see cref="requerimiento"/> and <see cref="requerimientoDTO"/>.
    /// </summary>
    public static partial class requerimientoAssembler
    {
      
        public static requerimiento ToEntity(this requerimientoDTO dto)
        {
            if (dto == null) return null;

            var entity = new requerimiento();

            entity.ID_Requerimiento = dto.ID_Requerimiento;
            entity.ID_Usuario = dto.ID_Usuario;
            entity.ID_Almacen = dto.ID_Almacen;
            entity.fecha = dto.fecha;
            entity.detalle_requerimiento = dto.detalle_requerimiento;
            entity.estado = dto.estado;
            entity.observaciones_requerimiento = dto.observaciones_requerimiento;

          

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="requerimiento"/> to an instance of <see cref="requerimientoDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="requerimiento"/> to convert.</param>
        public static requerimientoDTO ToDTO(this requerimiento entity)
        {
            if (entity == null) return null;

            var dto = new requerimientoDTO();

            dto.ID_Requerimiento = entity.ID_Requerimiento;
            dto.ID_Usuario = entity.ID_Usuario;
            dto.ID_Almacen = entity.ID_Almacen;
            dto.fecha = entity.fecha;
            dto.detalle_requerimiento = entity.detalle_requerimiento;
            dto.estado = entity.estado;
            dto.observaciones_requerimiento = entity.observaciones_requerimiento;

          

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="requerimientoDTO"/> to an instance of <see cref="requerimiento"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<requerimiento> ToEntities(this IEnumerable<requerimientoDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="requerimiento"/> to an instance of <see cref="requerimientoDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<requerimientoDTO> ToDTOs(this IEnumerable<requerimiento> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

        public static void Actualizar(Dominio.Dtos.requerimientoDTO dto, PersistenciaDatos.requerimiento entity)
        {
            entity.ID_Requerimiento = dto.ID_Requerimiento;
            entity.ID_Usuario = dto.ID_Usuario;
            entity.ID_Almacen = dto.ID_Almacen;
            entity.fecha = dto.fecha;
            entity.detalle_requerimiento = dto.detalle_requerimiento;
            entity.estado = dto.estado;
            entity.observaciones_requerimiento = dto.observaciones_requerimiento;

        }

    }
}
