//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class almacen
    {
        public almacen()
        {
            this.requerimiento = new HashSet<requerimiento>();
        }
    
        public int ID_Almacen { get; set; }
        public string year { get; set; }
        public string nombre_almacen { get; set; }
        public string direccion { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<requerimiento> requerimiento { get; set; }
    }
}
