//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogo
    {
        public catalogo()
        {
            this.requerimiento_detalle = new HashSet<requerimiento_detalle>();
        }
    
        public string ID_Catalogo { get; set; }
        public string tipo_bien { get; set; }
        public string unidad_medida { get; set; }
        public string nombre_bien { get; set; }
    
        public virtual ICollection<requerimiento_detalle> requerimiento_detalle { get; set; }
    }
}
