//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogo
    {
        public catalogo()
        {
            this.requerimiento_detalle = new HashSet<requerimiento_detalle>();
        }
    
        public string ID_Catalogo { get; set; }
        public string tipo_bien { get; set; }
        public string unidad_medida { get; set; }
        public string nombre_bien { get; set; }
    
        public virtual ICollection<requerimiento_detalle> requerimiento_detalle { get; set; }
    }
}
