//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class departamento
    {
        public departamento()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public int ID_Departamento { get; set; }
        public string nombre_departamento { get; set; }
    
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
