//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class entidad
    {
        public string Ruc { get; set; }
        public string nombre_entidad { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
    }
}
