//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDlogisticaEntities : DbContext
    {
        public BDlogisticaEntities()
            : base("name=BDlogisticaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<almacen> almacen { get; set; }
        public DbSet<catalogo> catalogo { get; set; }
        public DbSet<departamento> departamento { get; set; }
        public DbSet<entidad> entidad { get; set; }
        public DbSet<proyecto> proyecto { get; set; }
        public DbSet<requerimiento> requerimiento { get; set; }
        public DbSet<requerimiento_detalle> requerimiento_detalle { get; set; }
        public DbSet<unidad_medida> unidad_medida { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
