//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class requerimiento_detalle
    {
        public int ID_RequerimientoDetalle { get; set; }
        public Nullable<int> ID_Requerimiento { get; set; }
        public string ID_Catalogo { get; set; }
        public string ID_UnidadMedida { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<double> valor_referencial { get; set; }
    
        public virtual catalogo catalogo { get; set; }
        public virtual requerimiento requerimiento { get; set; }
        public virtual unidad_medida unidad_medida { get; set; }
    }
}
