//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class requerimiento
    {
        public requerimiento()
        {
            this.requerimiento_detalle = new HashSet<requerimiento_detalle>();
        }
    
        public int ID_Requerimiento { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public Nullable<int> ID_Almacen { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string detalle_requerimiento { get; set; }
        public string estado { get; set; }
        public string observaciones_requerimiento { get; set; }
    
        public virtual almacen almacen { get; set; }
        public virtual ICollection<requerimiento_detalle> requerimiento_detalle { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
