//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.proyecto = new HashSet<proyecto>();
            this.requerimiento = new HashSet<requerimiento>();
        }
    
        public int ID_Usuario { get; set; }
        public Nullable<int> ID_Departamento { get; set; }
        public string DNI { get; set; }
        public string password { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string email { get; set; }
        public string celular { get; set; }
        public string estado { get; set; }
    
        public virtual departamento departamento { get; set; }
        public virtual ICollection<proyecto> proyecto { get; set; }
        public virtual ICollection<requerimiento> requerimiento { get; set; }
    }
}
